### PR TITLE
frontend: wagmi/wc upgrade

### LINKED ISSUE #3: WalletConnect v2 support
We need to

- switch to use ConnectKit
- switch to use wagmi
- switch to use viem
- use WalletConnect v2

I will pay a 0.15 ETH bounty to whoever can submit a PR that does this.

### PR DESCRIPTION
**Pull request by malonehedges**
Resolves #3 

Needs a new environment variable for wallet connect support, `NEXT_PUBLIC_WALLET_CONNECT_ID`

### CODE REVIEW

**Comment by worm-emoji** [comment]
Taking a look. What is your ENS name?

**Comment by malonehedges** [comment]
mal1.eth!

**Comment by worm-emoji** [comment]
Redeploying the branch with the secret and testing now.

**Comment by worm-emoji** [comment]
Based on the logs, looks like we might still be on WalletConnect v1.

**Comment by malonehedges** [comment]
hm i was able to connect locally using a different project's wc id

**Comment by malonehedges** [comment]
i imagine the secret wasn't deployed properly or there's some allowed list of urls for a given walletconnect id

**Comment by worm-emoji** [comment]
yeah okay, i think the env var didn't save. redeployed and it works. 🏆  [you win](https://etherscan.io/tx/0xa8a140d218c911cc8df4bfbe9dc1a52cf5b4d3c1a38860d416b676cc4b81db9c)

**Comment by malonehedges** [comment]
🤝

**Pull request merged**
